# Generated by Django 4.0.4 on 2022-06-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_juegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleados',
            options={'verbose_name': 'empleado', 'verbose_name_plural': 'empleados'},
        ),
        migrations.AlterModelOptions(
            name='juguete',
            options={'verbose_name': 'juguete', 'verbose_name_plural': 'juguetes'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'sucursal', 'verbose_name_plural': 'sucursales'},
        ),
    ]
