# Generated by Django 4.0.4 on 2022-06-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_juegos', '0002_alter_empleados_options_alter_juguete_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juguete',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
