# Generated by Django 4.0.4 on 2022-06-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_juegos', '0003_juguete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='juguete',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
