# Generated by Django 4.0.4 on 2022-06-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_juegos', '0004_empleados_image_sucursal_image_alter_juguete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='juguete',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
