# Generated by Django 4.0.4 on 2022-07-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_juegos', '0006_remove_juguete_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='juguete',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
